api_login_check:
    path: /api/login_check
#SESSION
api_session:
    path: /api/v1/session
    controller: App\Controller\Shared\Session\SessionController
    methods: [GET]

#USER ENDPOINTS
api_create_user:
    path: /api/v1/user
    controller: App\Controller\User\CreateUserController
    methods: [POST]

api_get_user:
    path: /api/v1/user/{uuid}
    controller: App\Controller\User\GetUserByUuidController
    methods: [GET]

api_update_user:
    path: /api/v1/user/{uuid}
    controller: App\Controller\User\UpdateUserController
    methods: [PUT]

api_upload_user_avatar:
    path: /api/v1/user/{uuid}/avatar
    controller: App\Controller\User\UploadUserAvatarController
    methods: [POST]

api_search_user:
    path: /api/v1/user
    controller: App\Controller\User\SearchUserController
    methods: [GET]

#COMPANY ENDPOINTS
api_get_company:
    path: /api/v1/company
    controller: App\Controller\Company\GetCompanyController
    methods: [GET]
api_put_company:
    path: /api/v1/company
    controller: App\Controller\Company\UpdateCompanyController
    methods: [PUT]
#DEMO
demo:
    path: /demo
    controller: App\Controller\DemoController
    methods: [POST]
search-demo:
    path: /demo
    controller: App\Controller\SearchDemoController
    methods: [GET]

#ORGANIZATION ENDPOINTS
api_post_organization:
    path: /api/v1/organization
    controller: App\Controller\Organization\CreateOrganizationController
    methods: [POST]
api_search_organization:
    path: /api/v1/organization
    controller: App\Controller\Organization\SearchOrganizationController
    methods: [GET]
api_get_organization:
    path: /api/v1/organization/{uuid}
    controller: App\Controller\Organization\GetOrganizationByUuidController
    methods: [GET]
api_update_organization:
    path: /api/v1/organization/{uuid}
    controller: App\Controller\Organization\UpdateOrganizationController
    methods: [PUT]
