api_login_check:
    path: /api/login_check
#SESSION
api_session:
    path: /api/v1/session
    controller: App\Controller\Shared\Session\SessionController
    methods: [GET]

#USER ENDPOINTS
api_create_user:
    path: /api/v1/user
    controller: App\Controller\User\CreateUserController
    methods: [POST]

api_get_user:
    path: /api/v1/user/{uuid}
    controller: App\Controller\User\GetUserByUuidController
    methods: [GET]

api_update_user:
    path: /api/v1/user/{uuid}
    controller: App\Controller\User\UpdateUserController
    methods: [PUT]

demo:
    path: /demo
    controller: App\Controller\DemoController
    methods: [POST]
search-demo:
    path: /demo
    controller: App\Controller\SearchDemoController
    methods: [GET]