# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Controller\:
        resource: '../web/Controller/'
        tags: [ 'controller.service_arguments' ]

    Preventool\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #Command Bus
    _instanceof:
        Preventool\Domain\Shared\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        Preventool\Domain\Shared\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        Preventool\Domain\Shared\Bus\Event\EventHandler:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    #Security Listener
    Preventool\Infrastructure\Security\Listener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    Preventool\Infrastructure\Security\Listener\JWTAuthenticatedListener:
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_authenticated, method: onJWTAuthenticated }

    #Shared Listener
    Preventool\Infrastructure\Ui\Http\Listener\Shared\JsonTransformerExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

    #Repository
    Preventool\Domain\Demo\Repository\DemoRepository:
        class: Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineDemoRepository
        public: true
    Preventool\Domain\User\Repository\UserRepository:
        class: Preventool\Infrastructure\Persistence\Doctrine\Repository\User\DoctrineUserRepository
        public: true
