framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        failure_transport: failed
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers
            query.bus: ~
            message.bus: ~

        transports:
             failed: 'doctrine://default?queue_name=failed'
             sync: 'sync://'
             async:
                 dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                 options:
                     vhost: '%env(string:MESSENGER_VHOST)%'
                     exchange:
                         name: '%env(string:MESSENGER_EXCHANGE)%'
                         type: direct
                     queues:
                         main_queue:
                             binding_keys: [ main_queue ]

        routing:
            'Preventool\Domain\Shared\Bus\Command\Command': sync
            'Preventool\Domain\Shared\Bus\Query\Query': sync
            'Preventool\Domain\Shared\Bus\Event\Event': sync
            'Preventool\Domain\Shared\Bus\Message\Message': async


