framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers
            query.bus: ~
            message.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
             sync: 'sync://'

        routing:
            'Preventool\Domain\Shared\Bus\Command\Command': sync
            'Preventool\Domain\Shared\Bus\Query\Query': sync
            'Preventool\Domain\Shared\Bus\Event\Event': sync
            'Preventool\Domain\Shared\Bus\Message\Message': sync


